AWSTemplateFormatVersion: '2010-09-09'
Description: 'POC X-Ray - Database Stack (RDS PostgreSQL)'

Parameters:
  ProjectName:
    Type: String
    Default: xray-poc
    Description: Nome do projeto para tags

  NetworkStackName:
    Type: String
    Default: xray-poc-network
    Description: Nome da stack de rede

  DBUsername:
    Type: String
    Default: postgres
    Description: Database username

  DBPassword:
    Type: String
    NoEcho: true
    Default: postgres123
    MinLength: 8
    Description: Database password

Resources:
  # DB Subnet Group
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub ${ProjectName}-db-subnet-group
      DBSubnetGroupDescription: Subnet group for RDS database
      SubnetIds: !Split
        - ','
        - Fn::ImportValue: !Sub ${NetworkStackName}-PrivateSubnets
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-db-subnet-group

  # RDS Instance
  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub ${ProjectName}-database
      DBName: xraypoc
      DBInstanceClass: db.t3.micro
      Engine: postgres
      EngineVersion: '13.21'
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      AllocatedStorage: 20
      StorageType: gp2
      VPCSecurityGroups:
        - Fn::ImportValue: !Sub ${NetworkStackName}-RDSSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      BackupRetentionPeriod: 0
      MultiAZ: false
      PubliclyAccessible: false
      StorageEncrypted: false
      DeletionProtection: false
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-database

Outputs:
  DatabaseEndpoint:
    Description: RDS instance endpoint
    Value: !GetAtt Database.Endpoint.Address
    Export:
      Name: !Sub ${AWS::StackName}-DatabaseEndpoint

  DatabasePort:
    Description: RDS instance port
    Value: !GetAtt Database.Endpoint.Port
    Export:
      Name: !Sub ${AWS::StackName}-DatabasePort

  DatabaseName:
    Description: Database name
    Value: xraypoc
    Export:
      Name: !Sub ${AWS::StackName}-DatabaseName
